### ISSUE TITLE
Idempotence - Does not modify the service if it is already installed

### ISSUE THREAD

**Issue by axos88** [dhoer/chef-nssm#6]
If a service already exists, but the chef recipe is modified - the called program, or the arguments are changed for example, or one of the properties, the windows service is not updated, although it should.

**Comment by dhoer** [comment]
I don't remember if service_installed check is there because of issues with updating a service.  If you are able to update a service without issues, then I don't see a problem removing this constraint.  But please add test/fixtures/cookbooks/nssm_test/recipes/update_service.rb test to that verifies a nssm service can be updated.

**Comment by axos88** [comment]
Hmm. Even if it doesn't work chef should probably output a warning, or even a fatal error (or make it configurable). Silently ignoring that the desired state described by the recipe is different than the current state is a no-no imho.

I will create a pr later when I have some time.

**Comment by axos88** [comment]
Have you thought about deleting and recreating the service in such cases?

**Comment by dhoer** [comment]
I would try updating first, if that doesn't work, then recreate the service.
